# GitLab CI/CD Pipeline для автоматического обнаружения утечек памяти
# Автоматически запускается при push, merge request, по расписанию

stages:
  - prepare
  - build
  - test-quick
  - test-full
  - report
  - cleanup

variables:
  # Docker
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  
  # Python
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  
  # Test settings
  ALLURE_RESULTS_DIR: "tests/allure-results"
  ALLURE_REPORT_DIR: "tests/allure-report"

# Кеширование для ускорения
cache:
  paths:
    - .cache/pip
    - venv/

# ==========================================
# STAGE 1: Подготовка окружения
# ==========================================
prepare:
  stage: prepare
  image: python:3.11-slim
  before_script:
    - apt-get update -qq && apt-get install -y -qq git curl
  script:
    - echo "🔧 Подготовка Python окружения..."
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "✅ Окружение готово"
  artifacts:
    paths:
      - venv/
    expire_in: 1 hour

# ==========================================
# STAGE 2: Сборка Docker образов
# ==========================================
build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info
  script:
    - echo "🔨 Сборка Docker образов..."
    - docker-compose build --parallel
    - echo "✅ Образы собраны"
  artifacts:
    reports:
      junit: build-report.xml
  only:
    - main
    - merge_requests
    - develop

# ==========================================
# STAGE 3: Быстрые тесты (5 минут)
# ==========================================
test-quick:
  stage: test-quick
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  dependencies:
    - prepare
  before_script:
    - apk add --no-cache python3 py3-pip
    - source venv/bin/activate
  script:
    - echo "⚡ Запуск быстрых тестов на поиск утечек памяти..."
    - docker-compose up -d
    - echo "⏳ Ожидание готовности сервисов..."
    - sleep 30  # Даем время на старт
    - source venv/bin/activate
    - pytest tests/test_quick_demo.py -v -s --alluredir=$ALLURE_RESULTS_DIR --junitxml=quick-test-results.xml
    - echo "✅ Быстрые тесты завершены"
  after_script:
    - docker-compose down -v
  artifacts:
    when: always
    paths:
      - $ALLURE_RESULTS_DIR/
      - quick-test-results.xml
    reports:
      junit: quick-test-results.xml
    expire_in: 1 week
  only:
    - main
    - merge_requests

# ==========================================
# STAGE 4: Полные тесты (15 минут) - только на main
# ==========================================
test-full:
  stage: test-full
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  dependencies:
    - prepare
  before_script:
    - apk add --no-cache python3 py3-pip
    - source venv/bin/activate
  script:
    - echo "🧪 Запуск ПОЛНЫХ тестов на обнаружение утечек памяти (15 минут)..."
    - docker-compose up -d
    - sleep 30
    - source venv/bin/activate
    - pytest tests/test_memory_leak.py -v -s --alluredir=$ALLURE_RESULTS_DIR --junitxml=full-test-results.xml
    - echo "✅ Полные тесты завершены"
  after_script:
    - docker-compose down -v
  artifacts:
    when: always
    paths:
      - $ALLURE_RESULTS_DIR/
      - full-test-results.xml
    reports:
      junit: full-test-results.xml
    expire_in: 1 week
  timeout: 25m  # 25 минут таймаут
  only:
    - main  # Только на основной ветке
    - schedules  # И по расписанию
  when: manual  # Запуск вручную (можно убрать для автомата)

# ==========================================
# STAGE 5: Генерация Allure отчета
# ==========================================
report:
  stage: report
  image: openjdk:11-jre-slim
  dependencies:
    - test-quick
    - test-full
  before_script:
    - apt-get update -qq && apt-get install -y -qq wget
    - wget -q https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz
    - tar -zxf allure-2.24.1.tgz
    - chmod +x allure-2.24.1/bin/allure
  script:
    - echo "📊 Генерация Allure отчета..."
    - ./allure-2.24.1/bin/allure generate $ALLURE_RESULTS_DIR -o $ALLURE_REPORT_DIR --clean
    - echo "✅ Отчет сгенерирован"
    - ls -la $ALLURE_REPORT_DIR/
  artifacts:
    paths:
      - $ALLURE_REPORT_DIR/
    expire_in: 1 month
    reports:
      junit: "*.xml"
  # Публикуем отчет как GitLab Pages
  pages:
    stage: report
    dependencies:
      - report
    script:
      - mkdir public
      - cp -r $ALLURE_REPORT_DIR/* public/
    artifacts:
      paths:
        - public
    only:
      - main

# ==========================================
# STAGE 6: Очистка
# ==========================================
cleanup:
  stage: cleanup
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "🧹 Очистка Docker ресурсов..."
    - docker system prune -f
    - docker volume prune -f
    - echo "✅ Очистка завершена"
  when: always
  allow_failure: true

# ==========================================
# ДОПОЛНИТЕЛЬНЫЕ JOBS
# ==========================================

# Scheduled job - запуск полных тестов каждую ночь
nightly-tests:
  extends: test-full
  only:
    - schedules
  when: always
  script:
    - echo "🌙 Ночной запуск полных тестов..."
    - docker-compose up -d
    - sleep 60  # Больше времени на старт ночью
    - source venv/bin/activate
    - pytest tests/test_memory_leak.py -v -s --alluredir=$ALLURE_RESULTS_DIR --junitxml=nightly-results.xml
    - echo "✅ Ночные тесты завершены"

# Performance benchmark
performance-test:
  stage: test-full
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "⚡ Тестирование производительности..."
    - docker-compose up -d
    - sleep 30
    - |
      # Нагрузочное тестирование с Apache Bench
      apk add --no-cache apache2-utils
      echo "🔥 Тест нагрузки на приложение С утечкой..."
      ab -n 1000 -c 10 http://localhost:5000/api/cache > load-test-leak.txt
      echo "🔥 Тест нагрузки на приложение БЕЗ утечки..."
      ab -n 1000 -c 10 http://localhost:5001/api/cache > load-test-no-leak.txt
  artifacts:
    paths:
      - load-test-*.txt
    expire_in: 1 week
  only:
    - main
  when: manual

# Security scan
security-scan:
  stage: test-quick
  image: python:3.11-slim
  script:
    - echo "🔒 Проверка безопасности зависимостей..."
    - pip install safety bandit
    - safety check -r requirements.txt
    - bandit -r apps/ tests/ -f json -o security-report.json
  artifacts:
    paths:
      - security-report.json
    expire_in: 1 week
  allow_failure: true  # Не блокируем pipeline при проблемах безопасности