name: 🔍 Memory Leak Detection CI

on:
  # Запуск при push в main и PR
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  
  # Ручной запуск
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Тип тестов'
        required: true
        default: 'quick'
        type: choice
        options:
          - quick
          - full
          - performance
  
  # Расписание - каждую ночь в 2:00 UTC
  schedule:
    - cron: '0 2 * * *'

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  ALLURE_RESULTS_DIR: tests/allure-results

jobs:
  # ==========================================
  # JOB 1: Быстрые тесты (всегда)
  # ==========================================
  quick-tests:
    name: ⚡ Быстрые тесты (5 мин)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: 📥 Checkout код
      uses: actions/checkout@v4
      
    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: 📦 Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 🐳 Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: 🔨 Сборка и запуск сервисов
      run: |
        echo "🔨 Сборка Docker образов..."
        docker-compose build --parallel
        echo "🚀 Запуск сервисов..."
        docker-compose up -d
        echo "⏳ Ожидание готовности..."
        sleep 30
        docker-compose ps
        
    - name: ⚡ Запуск быстрых тестов
      run: |
        echo "🧪 Запускаем быстрые тесты на обнаружение утечек..."
        pytest tests/test_quick_demo.py -v -s \
          --alluredir=$ALLURE_RESULTS_DIR \
          --junitxml=quick-test-results.xml
          
    - name: 📊 Upload Allure результаты
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results-quick
        path: ${{ env.ALLURE_RESULTS_DIR }}/
        retention-days: 7
        
    - name: 📋 Публикация результатов тестов
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Quick Tests Results
        path: quick-test-results.xml
        reporter: java-junit
        
    - name: 🧹 Очистка
      if: always()
      run: docker-compose down -v

  # ==========================================
  # JOB 2: Полные тесты (только main)
  # ==========================================
  full-tests:
    name: 🧪 Полные тесты (15 мин)
    runs-on: ubuntu-latest
    timeout-minutes: 25
    if: github.ref == 'refs/heads/main' || github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.test_type == 'full')
    needs: quick-tests
    
    steps:
    - name: 📥 Checkout код
      uses: actions/checkout@v4
      
    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: 📦 Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 🐳 Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: 🔨 Сборка и запуск сервисов
      run: |
        docker-compose build --parallel
        docker-compose up -d
        sleep 60  # Больше времени для полных тестов
        
    - name: 🧪 Запуск полных тестов
      run: |
        echo "🔍 Запускаем ПОЛНЫЕ тесты на обнаружение утечек памяти..."
        pytest tests/test_memory_leak.py -v -s \
          --alluredir=$ALLURE_RESULTS_DIR \
          --junitxml=full-test-results.xml
          
    - name: 📊 Upload Allure результаты
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results-full
        path: ${{ env.ALLURE_RESULTS_DIR }}/
        retention-days: 30
        
    - name: 📋 Публикация результатов тестов
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Full Tests Results
        path: full-test-results.xml
        reporter: java-junit
        
    - name: 🧹 Очистка
      if: always()
      run: docker-compose down -v

  # ==========================================
  # JOB 3: Генерация Allure отчета
  # ==========================================
  allure-report:
    name: 📊 Allure отчет
    runs-on: ubuntu-latest
    if: always()
    needs: [quick-tests, full-tests]
    
    steps:
    - name: 📥 Download Allure результаты
      uses: actions/download-artifact@v3
      with:
        path: allure-results
        
    - name: 📊 Генерация Allure отчета
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_report: allure-report
        gh_pages: gh-pages
        allure_history: allure-history
        
    - name: 🚀 Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-history
        destination_dir: allure-report

  # ==========================================
  # JOB 4: Тесты производительности
  # ==========================================
  performance-tests:
    name: ⚡ Тестирование производительности
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.test_type == 'performance'
    
    steps:
    - name: 📥 Checkout код
      uses: actions/checkout@v4
      
    - name: 🔨 Сборка и запуск сервисов
      run: |
        docker-compose build --parallel
        docker-compose up -d
        sleep 30
        
    - name: ⚡ Apache Bench нагрузочное тестирование
      run: |
        sudo apt-get update && sudo apt-get install -y apache2-utils
        
        echo "🔥 Нагрузочный тест: Приложение С утечкой"
        ab -n 1000 -c 10 -g leak-app.tsv http://localhost:5000/api/stress > leak-app-results.txt
        
        echo "🔥 Нагрузочный тест: Приложение БЕЗ утечки"  
        ab -n 1000 -c 10 -g no-leak-app.tsv http://localhost:5001/api/stress > no-leak-app-results.txt
        
        echo "📊 Результаты нагрузочного тестирования:"
        echo "=== С УТЕЧКОЙ ==="
        tail -20 leak-app-results.txt
        echo "=== БЕЗ УТЕЧКИ ==="
        tail -20 no-leak-app-results.txt
        
    - name: 📊 Upload результаты производительности
      uses: actions/upload-artifact@v4
      with:
        name: performance-results
        path: |
          *-results.txt
          *.tsv
        retention-days: 7

  # ==========================================
  # JOB 5: Безопасность
  # ==========================================
  security-scan:
    name: 🔒 Сканирование безопасности
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout код
      uses: actions/checkout@v4
      
    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 🔒 Проверка зависимостей с Safety
      run: |
        pip install safety bandit
        safety check -r requirements.txt --json --output safety-report.json || true
        bandit -r apps/ tests/ -f json -o bandit-report.json || true
        
    - name: 📊 Upload результаты безопасности
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          safety-report.json
          bandit-report.json
        retention-days: 7

  # ==========================================
  # JOB 6: Уведомления
  # ==========================================
  notify:
    name: 📢 Уведомления
    runs-on: ubuntu-latest
    if: always()
    needs: [quick-tests, full-tests, allure-report]
    
    steps:
    - name: 📢 Slack уведомление
      uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        channel: '#memory-leak-ci'
        text: |
          🔍 Memory Leak Detection CI завершен
          
          📊 Статус тестов:
          • Быстрые тесты: ${{ needs.quick-tests.result }}
          • Полные тесты: ${{ needs.full-tests.result }}
          • Allure отчет: ${{ needs.allure-report.result }}
          
          🔗 Отчет: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/allure-report/
          
          Коммит: ${{ github.sha }}
          Ветка: ${{ github.ref }}
          Автор: ${{ github.actor }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        
    - name: 📧 Email уведомление при ошибке
      uses: dawidd6/action-send-mail@v3
      if: failure()
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "🔴 Memory Leak CI Failed: ${{ github.repository }}"
        to: ${{ secrets.EMAIL_TO }}
        from: Memory Leak CI
        body: |
          Обнаружена ошибка в Memory Leak Detection CI
          
          Репозиторий: ${{ github.repository }}
          Ветка: ${{ github.ref }}
          Коммит: ${{ github.sha }}
          Автор: ${{ github.actor }}
          
          Проверьте логи: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}